default_config:

logger:
  default: info
  logs:
    custom_components.multiscrape: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

multiscrape:
  - name: HA scraper
    resource: https://www.home-assistant.io
    scan_interval: 3600
    sensor:
      - unique_id: ha_latest_version
        name: Latest version
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) }}'
      - unique_id: ha_release_date
        icon: >-
          {% if is_state('binary_sensor.ha_version_check', 'on') %}
            mdi:alarm-light
          {% else %}
            mdi:bat
          {% endif %}
        name: Release date
        select: ".release-date"
    binary_sensor:
      - unique_id: ha_version_check
        name: Latest version == 2021.7.0
        select: ".current-version > h1:nth-child(1)"
        value_template: '{{ (value.split(":")[1]) | trim == "2021.7.0" }}'
        attributes:
          - name: Release notes link
            select: "div.links:nth-child(3) > a:nth-child(1)"
            attribute: href
 sensor:
  - platform: rest
    name: "AGSI+ Gasspeicher Deutschland"
    resource: "https://agsi.gie.eu/api?country=DE"
    scan_interval: 10800
    headers:
      x-key: 10d3a9efa38b5eecf6bae19182c4e369
      content-type: "application/json"
    value_template: "{{ value_json.data[0].full }}"
    unit_of_measurement: "%"
    json_attributes:
      - gasDayStart
      - gasInStorage
      - trend
      - consumption
      - injection
      - withdrawl
